// This file is auto-generated by generate-image-data.mjs
// Do not edit this file directly

export interface PortfolioImage {
  src: string;
  width: number;
  height: number;
  title?: string;
}

export const images: PortfolioImage[] = [
  {
    "src": "/images/portfolio/candle.png",
    "width": 2048,
    "height": 2048,
    "title": "Candle"
  },
  {
    "src": "/images/portfolio/charcuterie_board.png",
    "width": 2048,
    "height": 2048,
    "title": "Charcuterie Board"
  },
  {
    "src": "/images/portfolio/image10.jpg",
    "width": 3000,
    "height": 3000,
    "title": "Image10"
  },
  {
    "src": "/images/portfolio/image11.png",
    "width": 2048,
    "height": 1024,
    "title": "Image11"
  },
  {
    "src": "/images/portfolio/image12.jpg",
    "width": 2049,
    "height": 2048,
    "title": "Image12"
  },
  {
    "src": "/images/portfolio/image13.png",
    "width": 2000,
    "height": 2000,
    "title": "Image13"
  },
  {
    "src": "/images/portfolio/image14.png",
    "width": 2048,
    "height": 2048,
    "title": "Image14"
  },
  {
    "src": "/images/portfolio/image15.png",
    "width": 1600,
    "height": 2559,
    "title": "Image15"
  },
  {
    "src": "/images/portfolio/image16.png",
    "width": 2000,
    "height": 2000,
    "title": "Image16"
  },
  {
    "src": "/images/portfolio/image17.jpg",
    "width": 2048,
    "height": 2048,
    "title": "Image17"
  },
  {
    "src": "/images/portfolio/image18.jpg",
    "width": 1200,
    "height": 1200,
    "title": "Image18"
  },
  {
    "src": "/images/portfolio/image20.jpg",
    "width": 2048,
    "height": 2048,
    "title": "Image20"
  },
  {
    "src": "/images/portfolio/image21.png",
    "width": 2000,
    "height": 2000,
    "title": "Image21"
  },
  {
    "src": "/images/portfolio/image22.jpg",
    "width": 1920,
    "height": 1274,
    "title": "Image22"
  },
  {
    "src": "/images/portfolio/image24.jpg",
    "width": 2000,
    "height": 2000,
    "title": "Image24"
  },
  {
    "src": "/images/portfolio/image25.jpg",
    "width": 1200,
    "height": 1200,
    "title": "Image25"
  },
  {
    "src": "/images/portfolio/image27.jpg",
    "width": 1200,
    "height": 1200,
    "title": "Image27"
  },
  {
    "src": "/images/portfolio/image28.jpg",
    "width": 1167,
    "height": 937,
    "title": "Image28"
  },
  {
    "src": "/images/portfolio/image30.jpg",
    "width": 1200,
    "height": 1200,
    "title": "Image30"
  },
  {
    "src": "/images/portfolio/wine.png",
    "width": 2048,
    "height": 2048,
    "title": "Wine"
  },
  {
    "src": "/images/portfolio/woven_blanket_1.jpg",
    "width": 2048,
    "height": 2048,
    "title": "Woven Blanket 1"
  }
];
